### ISSUE TITLE
This is a fantastic implementation that should be submitted as nuget package

### ISSUE THREAD

**Issue by vhugogarcia** [chowarth/Prism.XCT.Popups#1]
I tested it on a local project and it worked very good on iOS and Android. THANK YOU for the implementation.

I highly recommend you to upload this as a nuget package, so others can install it in their projects. Honestly, it is a really nice work.

Thanks again!! 👍

**Comment by chowarth** [comment]
Thanks 😃 I purposefully didn't put this out as a package because I was hoping that a more official offering would be available soon but I'm not sure when that's likely to happen.

I can take a look at getting this into a package for those who want to use it - until there's a more official Prism package.

**Comment by chowarth** [comment]
@vhugogarcia I've published a package, with a slight name change: https://www.nuget.org/packages/XCT.Popups.Prism/ let me know if it's all good 👍🏼

**Comment by vhugogarcia** [comment]
Wonderful! I will remove the hardcoded classes and interfaces and replace them with this nuget package. 

Thank you so much for publishing it.

**Comment by mikesarmiento0423** [comment]
This is awesome! Thank you!
